#!/usr/bin/env node
// @ts-check
/**
 * adversario.mjs — R5: critico != autor. O Codex (OpenAI) tenta derrubar, linha
 * a linha, o veredicto que o Claude escreveu.
 *
 *   node _handoff/matriz-12-2026-09-10/adversario.mjs [--round N]
 *
 * Envia protocolo + veredicto + tabelas + defeitos + nao-provado, em cwd vazio,
 * read-only, sem o config pessoal do dono, e grava o prompt enviado e a resposta
 * integra. Nao reescreve nada: o autor le a resposta e decide o que aceita, e
 * escreve isso em `adversary.md` com o que mudou e o que nao mudou e porque.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chamarCodex } from './lib/codex-call.mjs';

const AQUI = path.dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
const round = argv.includes('--round') ? Number(argv[argv.indexOf('--round') + 1]) : 1;
const CAP = 30000;
const read = (f) => {
  try { const s = fs.readFileSync(path.join(AQUI, f), 'utf8'); return s.length > CAP ? s.slice(0, CAP) + `\n… [truncado a ${CAP} chars de ${s.length}]` : s; }
  catch { return null; }
};

const foco = [
  'You are the ADVERSARY (Codex, gpt-6-astra) for a pre-registered evidence package: MATRIZ 12, "Mooter vs the user\'s real choice". The author is a different engine (Claude Opus 5). Your job is to KNOCK DOWN the verdict, line by line, not to comment on it.',
  'Attack in particular: (1) "Haiku dominates the Mooter on both columns" — the Mooter\'s billed cost exceeds Haiku\'s ONLY because 2 of 12 prompts routed to Opus; is the comparison fair, or is it an artifact of the cost accounting (cache write of the CLI harness, list price vs subscription)? (2) the noise calibration: 2 points from 4 judge-pairs on 2 prompts — is that enough to call a 24-point gap "not noise"? (3) the judge family bias the author admits (J1 favours Codex, J2 favours Opus) — does it also contaminate the B-vs-C ordering, given both are Anthropic? (4) the pre-registered predictions: the author wrote the prompts AND copied the predictions; is "5 of 6 win-predictions failed, so the prompts were not rigged" a valid inference? (5) the four causes (route, code model, terse system prompt, inactive arbiter): are any of them unsupported by the data shown, and is the author hiding a fifth? (6) the 14-line patch to router-execute.js (D1): could it have changed anything beyond the token cap? (7) B2 (qwen3:30b) truncated at 2048 in 2 of 10 — does that invalidate the B vs B2 comparison? (8) anything in the wording an investor could read as a savings claim, a percentage, or a generalisation beyond 12 prompts on one machine.',
  'For EACH attack give: id (M12-NN), severity (fatal|serious|minor), the exact claim attacked (quote it), why it may not hold, and what evidence would settle it. Then: SURVIVE / REWORD / DEAD lists for the verdict\'s numbered claims ("O que esta corrida prova" 1-5). End with one line: VERDICT PUBLISHABLE AS IS / WITH THESE EDITS (list them) / NOT PUBLISHABLE. Be concrete and merciless; a review that only approves has not run. You have no repo access and no access to the raw responses: attack what is in front of you, and say explicitly what you could not verify.',
].join(' ');

const parts = [foco];
for (const [label, f] of [
  ['PROTOCOL (pre-registration, written before the run)', 'protocol.json'],
  ['VERDICT', 'verdict.md'],
  ['TABLES (generated by agregar.mjs, no cell written by hand)', 'TABELAS.md'],
  ['DEFECTS CAUGHT', '09-DEFEITOS-APANHADOS.md'],
  ['NOT PROVEN (written before seeing results)', '10-NAO-PROVADO.md'],
  ['PROMPTS', 'prompts.json'],
]) {
  const s = read(f);
  if (s) parts.push(`\n=== ${label} (${f}) ===\n${s}`);
}
const prompt = parts.join('\n');
const sufixo = round === 1 ? '' : `-round${round}`;
fs.writeFileSync(path.join(AQUI, `adversary-prompt-sent${sufixo}.txt`), prompt);

const arena = fs.mkdtempSync(path.join(os.tmpdir(), 'matriz12-adv-'));
const t0 = Date.now();
const r = chamarCodex({ prompt, cwd: arena, timeoutMs: 1200000 });
const s = Math.round((Date.now() - t0) / 1000);
const header = `<!-- adversary: codex exec (gpt-6-astra, effort medium), read-only, cwd vazio, --ignore-user-config, prompt por stdin; round ${round}; ok ${r.ok}; ${s} s; tokens in ${r.tokens_in ?? 'n/d'} (cached ${r.tokens_in_cached ?? 'n/d'}) out ${r.tokens_out ?? 'n/d'} reasoning ${r.tokens_reasoning ?? 'n/d'}; prompt_chars ${prompt.length}; at ${new Date().toISOString()} -->\n\n`;
fs.writeFileSync(path.join(AQUI, `adversary-codex-round${round}.md`), header + (r.texto || `(sem saida) motivo: ${r.motivo}`));
console.log(`round ${round}: ok=${r.ok} ${s}s tokens out ${r.tokens_out} → adversary-codex-round${round}.md`);
process.exit(r.ok ? 0 : 1);
