#!/usr/bin/env node
/**
 * classify.js — heuristic prompt classifier for the model router.
 *
 * Reads a prompt from argv[2] OR stdin. Emits JSON to stdout:
 *   { task_category, risk_level, recommended_backend, recommended_model,
 *     confidence, escalation_rule, reasoning, anthropic_key_present }
 *
 * Pure heuristics: zero LLM calls, <50ms. Designed to be safe — never blocks,
 * never throws (errors degrade to {recommended_backend: "claude_session"}).
 *
 * Tier mapping (see ~/.claude/docs/ROUTING_POLICY.md):
 *   T0 ollama   → local Ollama (qwen3:30b by default)
 *   T1 haiku    → Anthropic API direct (cheap Claude) — needs ANTHROPIC_API_KEY
 *   T2 sonnet   → Claude Code subagent with model: sonnet
 *   T3 opus     → Claude Code subagent with model: opus
 *   claude_session → just answer in the current Claude Code session (default)
 */

'use strict';

// ── TUNED-BLOCK-START (auto-generated by update-router.js) ──
// generated_at: 2026-04-17T03:19:47.017Z
// sample_size: 8503
const TUNED_COMPLEXITY_THRESHOLD = 0.3;
const TUNED_PROMOTE_T0 = [];
const TUNED_DEMOTE_T3 = [/\bpensa\s+bem\s+antes\b/i, /\bsonnet\s+diagnostica\s+este\b/i, /\bultrathink\s+this\s+problem\b/i];
// ── TUNED-BLOCK-END ──
// Note: backtest.js now filters tester events (source: mooter-tester) to
// prevent Ollama meta-prompt noise from poisoning promote/demote patterns.
// Review #2 (2026-04-17) cleaned up 48 toxic T0-promotes that caused T1→33.9%.

// ── ARCH_SIGNALS (mooter-review #2, 2026-04-16) ───────────────────────
// Architecture keywords that force T3 even when len<100 && triv==0
// would otherwise demote to T0 via line ~526 or TUNED_PROMOTE_T0.
// Requires 2+ matches to avoid single-keyword false positives like
// "design a logo" or "buy a system". The canonical failing prompt was
// "design a distributed payment system with stripe webhooks and fraud
// detection" (78 chars, no file hints) — previously routed to T0.
const ARCH_SIGNALS = [
  /\bdesign(?:ing|ed)?\b/i,
  /\bdistributed\b/i,
  /\bpayment(?:s)?\b/i,
  /\bsystem(?:s)?\b/i,
  /\bfraud\b/i,
  /\bscalab(?:le|ility)\b/i,
  /\bmulti[-\s]?tenant\b/i,
];

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// ── ALGORITHM VERSION (for retraining provenance) ──────────────────────
// Format: "v{semver}-{git_short_hash}" — computed once at load time.
const ALGORITHM_VERSION = (() => {
  try {
    const vPath = path.join(__dirname, 'version.json');
    const v = JSON.parse(fs.readFileSync(vPath, 'utf8')).version || '0.0.0';
    // Try git hash from __dirname first, then from CWD (covers both repo and runtime copies)
    const { execSync } = require('child_process');
    let hash = '';
    for (const cwd of [__dirname, process.cwd()]) {
      try { hash = execSync('git rev-parse --short HEAD', { cwd, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim(); if (hash) break; } catch {}
    }
    return `v${v}-${hash || 'local'}`;
  } catch { return 'v0.0.0-unknown'; }
})();

// SHA-256 cache — skip regex for identical prompts within 30min
const classifyCache = new Map();
const CACHE_TTL_MS = 30 * 60 * 1000;

function getCached(prompt) {
  const hash = crypto.createHash('sha256').update(prompt).digest('hex');
  const entry = classifyCache.get(hash);
  if (entry && Date.now() - entry.ts < CACHE_TTL_MS) {
    return { ...entry.result, cached: true };
  }
  return null;
}

function setCache(prompt, result) {
  const hash = crypto.createHash('sha256').update(prompt).digest('hex');
  classifyCache.set(hash, { result, ts: Date.now() });
  return result;
}

// MD Enrichment — read ## Router Context block from project CLAUDE.md
function readRouterContext() {
  const claudeMdPath = path.join(process.cwd(), 'CLAUDE.md');
  try {
    const content = fs.readFileSync(claudeMdPath, 'utf8');
    const match = content.match(/## Router Context\n([\s\S]*?)(?=\n## |\n# |$)/);
    if (!match) return {};

    const ctx = {};
    const lines = match[1].split('\n');
    for (const line of lines) {
      const [key, ...rest] = line.split(':');
      if (key && rest.length) {
        const val = rest.join(':').trim().replace(/#.*$/, '').trim();
        ctx[key.trim()] = val;
      }
    }
    return ctx;
  } catch {
    return {};
  }
}

// Per-tier model selection. T0 has FIVE models as of v0.10 (sub-tier specialists):
//   - ollama_terse:   small, fast, terse-output (summarization, transforms, quick)
//   - ollama_reason:  bigger, reasoning-trained (local analysis with 1-2 hops)
//   - ollama_general: best general-purpose local model (gemma4 when installed)
//   - ollama_code:    qwen2.5-coder:14b — dedicated local code specialist
//   - ollama_math:    deepseek-r1-distill-qwen:14b — dedicated local math/reasoning
//
// v0.10: gemma4:e4b added as preferred general model. It's Google's newest,
// with strong reasoning + multimodal + 128k context. Falls back to qwen2.5:3b
// if not installed. Sub-tier routing: code → ollama_code, math → ollama_math,
// reasoning → ollama_reason, general → ollama_general, quick → ollama_terse.
const MODELS = {
  ollama_terse:   process.env.ROUTER_OLLAMA_TERSE   || 'qwen2.5:3b',
  ollama_general: process.env.ROUTER_OLLAMA_GENERAL || 'gemma4:e4b',
  ollama_reason:  process.env.ROUTER_OLLAMA_REASON  || 'qwen3:30b',
  ollama_code:    process.env.ROUTER_OLLAMA_CODE    || 'qwen2.5-coder:14b',
  ollama_math:   process.env.ROUTER_OLLAMA_MATH   || 'deepseek-r1-distill-qwen:14b',
  ollama: process.env.ROUTER_OLLAMA_MODEL || 'qwen2.5:3b', // legacy alias
  haiku: process.env.ROUTER_ANTHROPIC_MODEL || 'claude-haiku-4-5-20251001',
  sonnet: 'claude-sonnet-4-6',
  opus: 'claude-opus-4-6',
};

// v0.7: pattern lists moved to patterns.js — single source of truth shared
// with backtest.js. Runtime behavior preserved exactly.
const { HIGH_RISK, MED_RISK, LOW_RISK, TRIVIAL } = require('./patterns');

const FILE_HINT = /\b(\w+\.(ts|tsx|js|jsx|py|go|rs|md|json|yml|yaml|sql|sh|css|html))\b/g;
const MULTI_FILE = /\bmulti[- ]?(arquivo|file)/i;

// ── USER OVERRIDE DETECTION ─────────────────────────────────────────────────
// "Usa o opus" / "force sonnet" / "@haiku" / "com ollama" / "sem opus" — let
// the user pin the model directly inside the prompt. Doctrine: explicit user
// intent always wins over heuristic tiering, EXCEPT when downgrading a prompt
// that carries a HIGH_RISK signal (refuses to route a deploy/migration to
// Ollama just because the user said so). Mirrors the dual-enforce guardrail
// pattern from the auto-learning loop.
//
// Vocabulary supported (PT-PT + EN):
//   positive  → use/usa/usar/com/with/via/por  + model
//   forced    → força/forçar/force/impõe       + model
//   short     → @opus / @sonnet / @haiku / @ollama / @gemini / @gpt
//   assign    → model[:=] opus / modelo[:=] sonnet
//   negative  → sem/no/não uses/don't use      + model  → demote one tier
//
// Models recognized → tier:
//   opus               → T3
//   sonnet             → T2
//   haiku              → T1
//   ollama|local|qwen  → T0
//   gemini             → T0 (Flash; use_pro flag bumps to T2)
//   gpt|gpt-4|gpt-4o   → T2 (informational backend, doctrine still routes
//                            via Anthropic subagent — will be live in v0.7)
const USER_OVERRIDE_MODELS = {
  opus:    { tier: 'T3', model: 'claude-opus-4-6',    backend: 'claude_subagent', label: 'Opus' },
  sonnet:  { tier: 'T2', model: 'claude-sonnet-4-6',  backend: 'claude_subagent', label: 'Sonnet' },
  haiku:   { tier: 'T1', model: 'claude-haiku-4-5',   backend: 'anthropic_api',   label: 'Haiku' },
  ollama:  { tier: 'T0', model: 'qwen2.5:3b',         backend: 'ollama',          label: 'Ollama' },
  local:   { tier: 'T0', model: 'qwen2.5:3b',         backend: 'ollama',          label: 'Ollama' },
  qwen:    { tier: 'T0', model: 'qwen2.5:3b',         backend: 'ollama',          label: 'Ollama' },
  gemini:  { tier: 'T0', model: 'gemini-2.5-flash',   backend: 'gemini',          label: 'Gemini' },
  gpt:     { tier: 'T2', model: 'gpt-4o',             backend: 'openai',          label: 'GPT' },
  'gpt-4': { tier: 'T2', model: 'gpt-4o',             backend: 'openai',          label: 'GPT-4o' },
  'gpt-4o':{ tier: 'T2', model: 'gpt-4o',             backend: 'openai',          label: 'GPT-4o' },
  claude:  { tier: 'T3', model: 'claude-opus-4-6',    backend: 'claude_subagent', label: 'Opus' }, // bare "claude" → opus
};

// Build a flat alternation regex of all model keywords for matching.
// Sorted longest-first so "gpt-4o" matches before "gpt".
const MODEL_KEYS_RE = Object.keys(USER_OVERRIDE_MODELS)
  .sort((a, b) => b.length - a.length)
  .join('|')
  .replace(/-/g, '\\-');

// Positive intents: "usa o opus", "use sonnet", "with claude", "via haiku",
// "por favor usa ollama", "rodar com gpt-4". Word boundary on the verb to
// avoid matching "usado" / "user", and an optional connector (o/a/the/o,a).
const POSITIVE_INTENT_RE = new RegExp(
  '\\b(?:usa|use|usar|usando|com|with|via|por\\s+favor\\s+usa|run\\s+with|rodar\\s+com|run\\s+on)' +
    '\\s+(?:o|a|the|um|uma)?\\s*(' + MODEL_KEYS_RE + ')\\b',
  'i'
);

// Forced intents: stronger language, same effect.
const FORCED_INTENT_RE = new RegExp(
  '\\b(?:for[çc]a|for[çc]ar|for[çc]a-?me|force|impo[ee]|impor)\\s+(?:o|a|um|uma)?\\s*(' +
    MODEL_KEYS_RE +
    ')\\b',
  'i'
);

// Short form: @opus, @sonnet, @haiku, @ollama, @gemini, @gpt-4o
const SHORT_FORM_RE = new RegExp('@(' + MODEL_KEYS_RE + ')\\b', 'i');

// Assignment form: "model: opus" / "modelo=sonnet" / "model = haiku"
const ASSIGN_RE = new RegExp(
  '\\bmodel(?:o)?\\s*[:=]\\s*(' + MODEL_KEYS_RE + ')\\b',
  'i'
);

// Negative intents: "sem opus", "no opus", "não uses opus", "don't use opus".
// These DEMOTE one tier (or pin lower) rather than pinning to a model.
const NEGATIVE_INTENT_RE = new RegExp(
  '\\b(?:sem|n[aã]o\\s+(?:uses|use|usar)|n[aã]o\\s+queiro|don\'?t\\s+use|do\\s+not\\s+use|no)\\s+(' +
    MODEL_KEYS_RE +
    ')\\b',
  'i'
);

function detectUserOverride(p) {
  if (!p || typeof p !== 'string') return null;

  // Check negative first — "sem opus" should not be matched as "opus" by the
  // positive regex. We strip the negative span before running positive checks.
  const neg = p.match(NEGATIVE_INTENT_RE);
  if (neg) {
    const blocked = neg[1].toLowerCase();
    return { kind: 'negative', blocked, raw: neg[0] };
  }

  // Forced > assigned > short > positive (priority order for same-prompt
  // multi-mention; first match wins via priority not source position).
  const forced = p.match(FORCED_INTENT_RE);
  if (forced) return { kind: 'forced', model: forced[1].toLowerCase(), raw: forced[0] };

  const assigned = p.match(ASSIGN_RE);
  if (assigned) return { kind: 'assigned', model: assigned[1].toLowerCase(), raw: assigned[0] };

  const short = p.match(SHORT_FORM_RE);
  if (short) return { kind: 'short', model: short[1].toLowerCase(), raw: short[0] };

  const positive = p.match(POSITIVE_INTENT_RE);
  if (positive) return { kind: 'positive', model: positive[1].toLowerCase(), raw: positive[0] };

  return null;
}

// ── QUALITY INTENT DETECTION (v0.7) ────────────────────────────────────────
// Natural-language quality/urgency signals that promote the tier one step
// without the user having to type "@opus" explicitly. Matches phrases like:
//   "Claude, preciso do teu melhor modelo para resolver isto"
//   "pensa bem antes de responder"
//   "think hard about this"
//   "ultrathink this problem"
//   "não podes falhar nisto"
//   "análise profunda"
//   "é crítico"
//
// Interaction rules (see classify() body):
//  - Promotion is capped at T3 (never above).
//  - User override (@opus etc.) still wins — quality_intent is advisory.
//  - HIGH_RISK downgrade refusal still applies (quality_intent can't save a
//    push/deploy from being T3 — it's already there).
//  - The `quality_intent` flag is emitted on the decision so the doctrine
//    reader can refuse to delegate to a lower-tier subagent.
const QUALITY_INTENT_PATTERNS = [
  // PT-PT
  /\b(?:preciso|quero|d[aá]-?\s*me|gostava\s+de)\s+(?:do|o|a)?\s*(?:teu|tua|vosso)?\s*melhor\b/i,
  /\b(?:pensa|reflecte|reflete|analisa|raciocina)\s+(?:bem|profund|com\s+cuidado|a\s+fundo|devagar)/i,
  /\bcom\s+(?:m[aá]xima|muita|toda\s+a)\s+(?:qualidade|aten[çc][aã]o|cuidado|precis[aã]o)/i,
  /\ban[aá]lise\s+(?:profund|detalhad|minucios|cuidados)/i,
  /\bn[aã]o\s+(?:podes\s+)?(?:falh|errar|te\s+engan)/i,
  /\b(?:[eé]\s+)?muito\s+cr[ií]tic/i,
  /\b(?:absolutamente|extremamente)\s+(?:importante|cr[ií]tico)/i,
  /\bd[aá]\s+o\s+teu\s+melhor\b/i,
  /\bresponde\s+(?:o\s+)?melhor\s+(?:que\s+)?(?:conseguires|possas|souberes)/i,
  // EN
  /\bthink\s+(?:hard|deeply|carefully|step[-\s]by[-\s]step|very\s+carefully)/i,
  /\bultrathink\b/i,
  /\bmega\s*think\b/i,
  /\bgive\s+(?:me\s+)?your\s+(?:best|top|finest)\s+(?:effort|model|shot|work|answer)?/i,
  /\bbe\s+(?:very\s+|extra\s+)?thoughtful\b/i,
  /\bdon'?t\s+(?:mess|screw|fuck)\s+(?:this|it)\s+up/i,
  /\b(?:this\s+is\s+)?mission[-\s]critical\b/i,
  /\bproduction[-\s](?:code|fix|deploy|critical)/i,
  /\b(?:high|top)\s+priority\b/i,
  /\bmaximum\s+(?:quality|effort|care)/i,
  /\bdeep(?:[-\s]dive)?\s+(?:analysis|investigation)/i,
];

// ── SUB-TIER CONTENT PATTERNS (v0.7) ───────────────────────────────────────
// When a prompt lands in T0, we select a local specialist model based on
// content: code work → qwen2.5-coder:14b, math/reasoning → deepseek-r1, else
// the general qwen2.5:3b. Patterns are deliberately broad so the classifier
// catches common phrasings without over-escalating.
//
// Code signals: function/class keywords, file extensions, programming verbs.
const CODE_SUBTIER_RE = /\b(?:function|class|import|export|const|let|var|async|await|return|def|if\s+__name__|struct|impl|trait|interface|fn\s+|pub\s+|package\s+|public\s+class)\b|\b(?:refactor|rename|extract|inline|debug|compile|lint|typecheck|transpile)\b|\b\w+\.(?:ts|tsx|js|jsx|py|go|rs|java|c|cpp|h|hpp|rb|php|swift|kt|dart|scala|cs|sh|bash|zsh|sql|yaml|yml|toml|gradle|cmake)\b/i;

// Math signals: operators, equation keywords, calculation verbs.
const MATH_SUBTIER_RE = /\b(?:calcula(?:r|\s+a)?|compute|solve\s+(?:for|the)?|prove(?:\s+that)?|deriv[ae]|integral|integra(?:l|\s+de)?|equa[çc][aã]o|equation|theorem|lemma|corol[aá]rio|matrix|matriz|vetor|vector|determinant|eigenvalue|polin[oó]mio|polynomial|trigonom|logari[tm]|sin|cos|tan|limit\s+as|lim\s+_|sum\s+from|soma\s+de|sigma)\b|[∫∑∏∂∇√≤≥≠≈±∞]/i;
// Tier T0 — local read or simple bash, no need for Opus.
const BASH_PASTE = /^\s*(?:cat|ls|cd|grep|rg|find|sed|awk|head|tail|cp|mv|mkdir|touch|echo|pwd|tree|wc|sort|uniq|diff|chmod|chown|tar|zip|unzip|curl|wget|ping|nslookup|ps|kill|top|df|du|env|export|source|history|which(?=\s+\S+\s*$)|whereis|node|npm|npx|pnpm|yarn|python|python3|pip|pip3|git|docker|kubectl|systemctl|service|brew|apt|apt-get|yum|dnf|psql|mysql|redis-cli|sqlite3)\s/;

// PowerShell paste pattern (very common in this user's history)
const PS_PASTE = /^(?:PS\s+[A-Z]:\\|>\s*$)/m;

// Cat / read file: explicit read intent — pure T0
const READ_INTENT = /^\s*(?:lê|ler|le|read|abre|cat|view|show|mostra)\s+[\w./\\-]+/i;

function readPrompt() {
  const fromArg = process.argv.slice(2).join(' ').trim();
  if (fromArg) return Promise.resolve(fromArg);
  return new Promise((resolve) => {
    let data = '';
    if (process.stdin.isTTY) return resolve('');
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => (data += chunk));
    process.stdin.on('end', () => resolve(data.trim()));
  });
}

// ── PROMPT FEATURE EXTRACTION (v0.9.1) ────────────────────────────────────
// Derives boolean/numeric features from the prompt WITHOUT storing text.
// Used for enriching decisions.log and future classifier improvements.
const PT_TOKENS = /\b(?:porqu[eê]|preciso|podes|tenho|est[aá]|estou|vou|fazer|como|quando|porque|consegues|tens|deves|quero|precisas|mostra|ajuda)\b/i;

function extractPromptFeatures(text) {
  const t = text || '';
  return {
    has_code_block: /```[\s\S]{10,}```/.test(t) || /`[^`]{3,}`/.test(t),
    has_file_refs: /\b\w+\.(ts|js|py|go|rs|java|md|json|yaml|toml|env)\b/.test(t),
    file_ref_count: Math.min((t.match(/\b\w+\.(ts|js|py|go|rs|java|md|json|yaml)\b/g) || []).length, 10),
    lang_detected: (t.match(new RegExp(PT_TOKENS.source, 'gi')) || []).length >= 2 ? 'pt' : /\b(?:why|how|please|can you|make|create|should|would|could)\b/i.test(t) ? 'en' : 'other',
    has_error_trace: /at \w+\s*\([\w/:.]+:\d+:\d+\)/.test(t) || /(?:Error|TypeError|ReferenceError|SyntaxError):/.test(t),
    is_question: /[?？]\s*$/.test(t.trim()),
    has_url: /https?:\/\//.test(t),
  };
}

// ── COMPLEXITY SCORE (0.0-1.0) ─────────────────────────────────────────
// Composite score for retraining: groups "easy T0" vs "hard T0".
// Inputs: prompt length, file refs, risk signal counts, prompt features.
// NOT a quality metric — just how "complex" the prompt appears structurally.
function computeComplexity(len, fileMatches, high, med, low, features) {
  let score = 0;
  // Length contribution (0-0.3): longer prompts are structurally more complex
  score += Math.min(0.3, (len / 2000) * 0.3);
  // File reference contribution (0-0.15): more files = more scope
  score += Math.min(0.15, fileMatches * 0.05);
  // Risk signal contribution (0-0.3): high/med signals indicate complexity
  score += Math.min(0.3, high * 0.15 + med * 0.08 + low * 0.02);
  // Code block contribution (0-0.1)
  if (features && features.has_code_block) score += 0.1;
  // Error trace contribution (0-0.1)
  if (features && features.has_error_trace) score += 0.1;
  // Question mark (0-0.05): questions are slightly more complex than commands
  if (features && features.is_question) score += 0.05;
  return Math.round(Math.min(1.0, score) * 1000) / 1000;
}

function classify(prompt) {
  const cached = getCached(prompt || '');
  if (cached) return cached;

  const p = prompt || '';
  const len = p.length;
  const fileMatches = (p.match(FILE_HINT) || []).length;
  const multiFile = MULTI_FILE.test(p) || fileMatches > 3;

  const hits = (rxs) => rxs.reduce((n, r) => n + (r.test(p) ? 1 : 0), 0);
  const high = hits(HIGH_RISK);
  const med = hits(MED_RISK);
  const low = hits(LOW_RISK);
  const triv = hits(TRIVIAL);

  let tier;
  let category;
  let risk;
  let confidence;
  let reasoning;

  // Early-exit fast paths discovered from real-corpus replay (v3 tuning).
  // These patterns dominate real history and were previously misclassified
  // as ambiguous_default → escalated to T3 unnecessarily.
  //
  // SAFETY: early-returns are GATED by HIGH_RISK pre-check (added Sprint B.0).
  // Before this fix, `git reset --hard` hit BASH_PASTE and returned T0 conf=0.9,
  // bypassing the HIGH_RISK guardrail entirely. Same for `abre um PR ... merge`
  // hitting READ_INTENT. Now: if ANY HIGH_RISK signal fires, early-returns are
  // skipped and the full classification pipeline runs.
  if (high === 0 && (BASH_PASTE.test(p) || PS_PASTE.test(p))) {
    return {
      task_category: 'bash_command_paste',
      risk_level: 'minimal',
      tier: 'T0',
      recommended_backend: 'ollama',
      recommended_model: MODELS.ollama_terse,
      suggested_subagent: 'local-transformer',
      confidence: 0.9,
      escalation_rule: 'none',
      reasoning: 'bash/powershell command paste — no LLM reasoning needed',
      anthropic_key_present: !!process.env.ANTHROPIC_API_KEY,
      prompt_length: len,
      file_hint_count: fileMatches,
    };
  }
  if (high === 0 && READ_INTENT.test(p) && len < 200) {
    return {
      task_category: 'file_read_intent',
      risk_level: 'minimal',
      tier: 'T0',
      recommended_backend: 'ollama',
      recommended_model: MODELS.ollama_terse,
      suggested_subagent: 'local-summarizer',
      confidence: 0.85,
      escalation_rule: 'none',
      reasoning: 'explicit file read with no further reasoning required',
      anthropic_key_present: !!process.env.ANTHROPIC_API_KEY,
      prompt_length: len,
      file_hint_count: fileMatches,
    };
  }

  // Fast-path: commit message generation → T1 (cheap-triage subagent).
  // Without this, the LOW_RISK hit sets T1 but the no-API-key guardrail
  // (line ~510) degrades it to T0. cheap-triage works without ANTHROPIC_API_KEY
  // because it runs as a Claude Code subagent, not a direct Haiku call.
  if (/\bcommit\s+(message|msg)\b/i.test(p) || /\bgera\s+(mensagem|msg)\s+de\s+commit/i.test(p)) {
    return {
      task_category: 'cheap_task',
      risk_level: 'low',
      tier: 'T1',
      recommended_backend: 'claude_subagent',
      recommended_model: 'claude-haiku-4-5-20251001',
      suggested_subagent: 'cheap-triage',
      confidence: 0.9,
      escalation_rule: 'none',
      reasoning: 'commit message generation — cheap-triage handles this well',
      anthropic_key_present: !!process.env.ANTHROPIC_API_KEY,
      prompt_length: len,
      file_hint_count: fileMatches,
    };
  }

  // ── CONTEXT-AWARE OVERRIDES (mooter-review #1, 2026-04-16) ─────────────
  // These fast-paths fire BEFORE the HIGH_RISK escalation to handle cases
  // where a HIGH_RISK keyword appears in a non-risky context.

  // "write a regex that matches <anything>" — regex task even if <anything>
  // contains architecture keywords like CQRS, hexagonal, GraphQL, etc.
  if (/\b(?:write|build|create|gera)\s+(?:a\s+|uma?\s+)?regex\b/i.test(p) && !multiFile) {
    return setCache(p, {
      task_category: 'cheap_task',
      risk_level: 'low',
      tier: 'T1',
      recommended_backend: 'claude_subagent',
      recommended_model: 'claude-haiku-4-5-20251001',
      suggested_subagent: 'cheap-triage',
      confidence: 0.85,
      escalation_rule: 'regex_task_override',
      reasoning: 'regex generation — T1 regardless of keyword content',
      anthropic_key_present: !!process.env.ANTHROPIC_API_KEY,
      prompt_length: len,
      file_hint_count: fileMatches,
    });
  }

  // "explain the difference between X and Y" — explanation, not architecture decision.
  // Only fires for short prompts (<250 chars) with no other high-risk context.
  if (/\bexplain\s+(?:the\s+)?difference\s+between\b/i.test(p) && len < 250 && !multiFile) {
    return setCache(p, {
      task_category: 'simple_transform_or_explain',
      risk_level: 'low',
      tier: 'T1',
      recommended_backend: 'claude_subagent',
      recommended_model: 'claude-haiku-4-5-20251001',
      suggested_subagent: 'cheap-triage',
      confidence: 0.8,
      escalation_rule: 'explain_difference_override',
      reasoning: 'explaining a concept difference — T1 explanation task',
      anthropic_key_present: !!process.env.ANTHROPIC_API_KEY,
      prompt_length: len,
      file_hint_count: fileMatches,
    });
  }

  // "show me / read / lê the package.json" — read-only intent on package.json.
  // package.json is HIGH_RISK for edits, but reading it is T0.
  if (READ_INTENT.test(p) && /\bpackage\.json\b/.test(p) && len < 200
      && !/\b(?:edit|change|add|remove|update|install|uninstall|modifica|altera|adiciona)\b/i.test(p)) {
    return setCache(p, {
      task_category: 'file_read_intent',
      risk_level: 'minimal',
      tier: 'T0',
      recommended_backend: 'ollama',
      recommended_model: MODELS.ollama_terse,
      suggested_subagent: 'local-summarizer',
      confidence: 0.85,
      escalation_rule: 'package_json_read_override',
      reasoning: 'read-only intent on package.json — safe T0',
      anthropic_key_present: !!process.env.ANTHROPIC_API_KEY,
      prompt_length: len,
      file_hint_count: fileMatches,
    });
  }

  // "translate this X to Y" — translation is T0/T1, even if X contains keywords.
  if (/\b(?:translate|traduz)\b/i.test(p) && len < 200
      && !/\b(?:migrat|refactor|rewrite|redesign)\b/i.test(p)) {
    return setCache(p, {
      task_category: 'trivial_local',
      risk_level: 'minimal',
      tier: 'T0',
      recommended_backend: 'ollama',
      recommended_model: MODELS.ollama_terse,
      suggested_subagent: 'local-transformer',
      confidence: 0.85,
      escalation_rule: 'translation_override',
      reasoning: 'translation task — T0 regardless of content keywords',
      anthropic_key_present: !!process.env.ANTHROPIC_API_KEY,
      prompt_length: len,
      file_hint_count: fileMatches,
    });
  }

  if (high > 0 || multiFile || /\barchitect|arquitetur/i.test(p)) {
    tier = 'T3';
    category = multiFile ? 'cross_file_change' : 'architecture_or_critical';
    risk = 'high';
    confidence = high >= 2 ? 0.9 : 0.75;
    reasoning = `high-risk signals: ${high}, multiFile: ${multiFile}`;
  } else if (med > 0 && med >= low) {
    tier = 'T2';
    category = 'reasoning_intermediate';
    risk = 'medium';
    confidence = 0.7;
    reasoning = `medium-risk reasoning signals: ${med}`;
  } else if (low > 0 && high === 0) {
    tier = 'T1';
    category = 'simple_transform_or_explain';
    risk = 'low';
    confidence = len < 200 ? 0.85 : 0.7;
    reasoning = `low-risk signals: ${low}, len=${len}`;
  } else if (triv > 0 || (len < 120 && fileMatches === 0)) {
    tier = 'T0';
    category = 'trivial_local';
    risk = 'minimal';
    confidence = 0.8;
    reasoning = `trivial signals: ${triv}, len=${len}`;
  } else {
    // Ambiguous: lean toward the cheapest tier that's still safe.
    // v3 fix: real-corpus replay showed 27% of prompts hit this branch and
    // were being escalated +1 tier to T3, which destroyed savings. Most
    // ambiguous prompts are short to medium and don't need Opus.
    //
    // TUNED_COMPLEXITY_THRESHOLD (from daily backtest) scales the char cutoffs.
    // Baseline = 0.3. Lower threshold ⇒ more aggressive (widens T0 window).
    // Higher threshold ⇒ more conservative (narrows T0 window).
    // scale = 0.3 / threshold, clamped to [0.7, 1.5] to avoid runaway tuning.
    const rawScale =
      typeof TUNED_COMPLEXITY_THRESHOLD === 'number' && TUNED_COMPLEXITY_THRESHOLD > 0
        ? 0.3 / TUNED_COMPLEXITY_THRESHOLD
        : 1;
    const ambigScale = Math.max(0.7, Math.min(1.5, rawScale));
    const shortCutoff = Math.round(250 * ambigScale);
    const mediumCutoff = Math.round(600 * ambigScale);
    if (len < shortCutoff && fileMatches <= 1) {
      tier = 'T0';
      category = 'ambiguous_short';
      risk = 'minimal';
      confidence = 0.65;
      reasoning = `short ambiguous prompt — safe to start in local tier (cutoff=${shortCutoff})`;
    } else if (len < mediumCutoff) {
      // v0.9.3 fix: was T2 (Sonnet), now T1 (Haiku). Ambiguous prompts without
      // MED_RISK signals don't need Sonnet-level reasoning — Haiku handles them
      // fine. This closes the T1 gap (was 0% of all prompts) and improves savings.
      tier = 'T1';
      category = 'ambiguous_medium';
      risk = 'low';
      confidence = 0.6;
      reasoning = `medium ambiguous prompt — Haiku handles this fine (cutoff=${mediumCutoff})`;
    } else {
      // v0.9.3 fix: long ambiguous without risk signals → T1 not T2.
      // Sonnet reserved for prompts with actual MED_RISK evidence.
      tier = 'T1';
      category = 'ambiguous_long';
      risk = 'low';
      confidence = 0.55;
      reasoning = 'long ambiguous prompt — Haiku, escalate manually if needed';
    }
  }

  // Guardrail: low confidence escalates 1 tier ONLY if there's at least 1
  // medium-risk signal. v3 fix: previously this rule auto-escalated 27% of
  // the corpus to T3 with no risk evidence, destroying savings. Now we
  // require evidence before paying for Opus.
  let escalation_rule = 'none';
  if (confidence < 0.5 && tier !== 'T3' && (med > 0 || high > 0)) {
    const order = ['T0', 'T1', 'T2', 'T3'];
    tier = order[order.indexOf(tier) + 1];
    escalation_rule = 'low_confidence_with_risk_signal_+1_tier';
  }

  // TUNED promote pass — backtest discovers patterns that are consistently
  // wasted on T1/T2/T3 and injects regexes into TUNED_PROMOTE_T0. Same
  // high-risk guardrail applies: never promote a prompt that carries any
  // HIGH_RISK signal, regardless of what the backtest learned.
  if (
    Array.isArray(TUNED_PROMOTE_T0) &&
    TUNED_PROMOTE_T0.length > 0 &&
    tier !== 'T0' &&
    high === 0 &&
    TUNED_PROMOTE_T0.some((rx) => rx.test(p))
  ) {
    tier = 'T0';
    category = 'tuned_promote_local';
    risk = 'minimal';
    escalation_rule =
      escalation_rule === 'none'
        ? 'tuned_promote_from_backtest'
        : `${escalation_rule}+tuned_promote`;
    reasoning = `${reasoning}; tuned_promote → T0 (pattern match from backtest)`;
  }

  // ── ARCH_SIGNALS guard (mooter-review #2) ──────────────────────────────
  // Architecture prompts force T3 even when trivial signals / short length
  // would otherwise demote them (including via TUNED_PROMOTE_T0 above).
  // Runs AFTER TUNED_PROMOTE_T0 so it overrides any stray demotion.
  const archHits = ARCH_SIGNALS.reduce((n, rx) => n + (rx.test(p) ? 1 : 0), 0);
  if (archHits >= 2 && tier !== 'T3') {
    tier = 'T3';
    category = 'architecture_or_critical';
    risk = 'high';
    confidence = Math.max(confidence, 0.85);
    escalation_rule =
      escalation_rule === 'none'
        ? 'arch_signals_force_t3'
        : `${escalation_rule}+arch_signals_force_t3`;
    reasoning = `${reasoning}; arch_signals (${archHits} matches) → forced T3`;
  }

  // ── QUALITY INTENT PROMOTION (v0.7) ────────────────────────────────────
  // Natural-language signal that the user wants a more capable model without
  // explicitly typing "@opus". Promotes one tier (capped at T3).
  // Note: this runs BEFORE user_override handling. If the user ALSO typed
  // "@haiku", the override block below will win and pin to Haiku as requested.
  let qualityIntent = false;
  if (QUALITY_INTENT_PATTERNS.some((rx) => rx.test(p))) {
    qualityIntent = true;
    const TIER_LADDER = ['T0', 'T1', 'T2', 'T3'];
    const idx = TIER_LADDER.indexOf(tier);
    if (idx >= 0 && idx < TIER_LADDER.length - 1) {
      tier = TIER_LADDER[idx + 1];
      escalation_rule =
        escalation_rule === 'none'
          ? 'quality_intent_promote'
          : `${escalation_rule}+quality_intent_promote`;
      reasoning = `${reasoning}; quality_intent detected (natural language) → promoted to ${tier}`;
      confidence = Math.max(confidence, 0.75);
    } else {
      reasoning = `${reasoning}; quality_intent detected but already at ${tier}`;
    }
  }

  // Beast-mode intent — user signals cost is irrelevant, wants maximum quality.
  // Unlike quality_intent (promote +1), this PINS to T3 directly.
  const BEAST_INTENT = [
    /\bn[aã]o\s+(?:me\s+)?import[ao]\s+(?:com\s+)?(?:o\s+)?(?:dinheiro|cu[s]to|preço|price|money)/i,
    /\b(?:beast|gsd)\s+mode\b/i,
    /\bvelocidade\s+m[aá]xima\b/i,
    /\bfor[çc]a\s+opus\b/i,
    /\bquero\s+opus\b/i,
    /\buse\s+(?:the\s+)?best\s+(?:model|llm)\b/i,
    /\bfull\s+power\b/i,
    /\bdon'?t\s+(?:care|worry)\s+about\s+(?:cost|money|price|budget)/i,
    // A/B test 2026-04-16 — P10: "Não me importo com o custo" not detected
    /\bcusto\s+n[aã]o\s+(?:me\s+)?interessa/i,  // "custo não interessa"
    /\bn[aã]o\s+poupes\b/i,                       // "não poupes" — don't save
    /\bpreciso\s+d[ao]\s+melhor/i,                 // "preciso da melhor análise"
    /\bgive\s+me\s+(?:your\s+)?best/i,            // "give me your best"
    /\bmelhor\s+an[aá]lise\s+poss[ií]vel/i,       // "melhor análise possível"
  ];
  if (!qualityIntent && BEAST_INTENT.some((rx) => rx.test(p))) {
    tier = 'T3';
    escalation_rule =
      escalation_rule === 'none'
        ? 'beast_intent_force_t3'
        : `${escalation_rule}+beast_intent_force_t3`;
    reasoning = `${reasoning}; beast-mode intent detected → forced T3`;
    confidence = Math.max(confidence, 0.85);
  }

  // TUNED demote pass — auto-learning backtest discovers patterns that are
  // consistently over-routed to T2/T3 and injects regexes into TUNED_DEMOTE_T3.
  // If a pattern matches, force the suggested tier down to T1 (Haiku) to
  // recover savings. Runs AFTER quality_intent so that explicit user intent
  // ("pensa bem") is never silently cancelled by auto-tuning.
  if (
    Array.isArray(TUNED_DEMOTE_T3) &&
    TUNED_DEMOTE_T3.length > 0 &&
    (tier === 'T2' || tier === 'T3') &&
    high === 0 && // doctrine guardrail: never demote prompts with high-risk signals
    !qualityIntent && // never override explicit user quality intent
    TUNED_DEMOTE_T3.some((rx) => rx.test(p))
  ) {
    tier = 'T1';
    escalation_rule =
      escalation_rule === 'none'
        ? 'tuned_demote_from_backtest'
        : `${escalation_rule}+tuned_demote`;
    reasoning = `${reasoning}; tuned_demote → T1 (pattern match from backtest)`;
  }

  // Sprint B.2: per-user budget cap from user-profile.json.
  // If monthly spend exceeds the cap, downgrade tier (never below T0).
  // HIGH_RISK and quality_intent are exempt — safety and explicit user
  // intent always win over budget.
  try {
    const profilePath = path.join(
      process.env.HOME || process.env.USERPROFILE || '.',
      '.claude', 'tools', 'router', 'user-profile.json'
    );
    if (fs.existsSync(profilePath)) {
      const profile = JSON.parse(fs.readFileSync(profilePath, 'utf8'));
      const cap = profile.budget && profile.budget.monthly_budget_usd;
      const spent = profile.budget && profile.budget.monthly_spent_usd;
      if (typeof cap === 'number' && cap > 0 && typeof spent === 'number') {
        const pct = spent / cap;
        const capBehavior = (profile.budget && profile.budget.hard_cap_behavior) || 'downgrade_one_tier';
        if (pct >= 0.95 && high === 0 && !qualityIntent && capBehavior === 'downgrade_one_tier') {
          const TIER_LADDER = ['T0', 'T1', 'T2', 'T3'];
          const idx = TIER_LADDER.indexOf(tier);
          if (idx > 0) {
            tier = TIER_LADDER[idx - 1];
            escalation_rule = escalation_rule === 'none'
              ? 'budget_cap_downgrade'
              : `${escalation_rule}+budget_cap_downgrade`;
            reasoning = `${reasoning}; budget ${(pct * 100).toFixed(0)}% spent → downgraded to ${tier}`;
          }
        }
      }
    }
  } catch { /* profile read is best-effort */ }

  const anthropicKey = !!process.env.ANTHROPIC_API_KEY;
  // v0.10: T1 provider check — degrade to T0 ONLY if NO cheap provider is available.
  // Before v0.10: T1 degraded whenever ANTHROPIC_API_KEY was absent.
  // Now: any alternative T1 provider (DeepSeek, Gemini, Mistral, OpenAI) keeps T1 alive.
  // Claude subagent (Haiku via cheap-triage) also works without ANTHROPIC_API_KEY.
  const hasAnyT1Provider = anthropicKey
    || !!process.env.DEEPSEEK_API_KEY
    || !!(process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY)
    || !!process.env.MISTRAL_API_KEY
    || !!process.env.OPENAI_API_KEY;

  // v0.10.1: Only degrade T1→T0 when NO provider is available AND Ollama is the fallback.
  // When alternative T1 providers exist, keep T1 — UNLESS the task is trivial (LOW_RISK only,
  // no MED_RISK). Trivial tasks stay on Ollama (free) even when cloud keys are available.
  const trivialOnlyT1 = low > 0 && med === 0 && high === 0;
  const ollamaAvailable = true; // assume Ollama is available if hw-capability exists
  if (tier === 'T1' && !anthropicKey && (!hasAnyT1Provider || (trivialOnlyT1 && ollamaAvailable))) {
    if (qualityIntent) {
      tier = 'T2';
      escalation_rule =
        escalation_rule === 'none'
          ? 'quality_intent_jump_t2_no_haiku_key'
          : `${escalation_rule}+quality_intent_jump_t2`;
    } else {
      tier = 'T0';
      escalation_rule = 'haiku_unavailable_no_provider_degraded_to_local';
    }
  }

  // ── T0 SUB-TIER SELECTION (v0.10) ──────────────────────────────────────
  // At T0, pick the best local model by content intent:
  //   - code signals  → qwen2.5-coder:14b
  //   - math signals  → deepseek-r1-distill-qwen:14b
  //   - reasoning degraded from T1/T2 → qwen3:30b (heavy reasoning)
  //   - general/summarize/explain → gemma4:e4b (best overall local model)
  //   - quick terse (Option A target) → qwen2.5:3b
  //
  // v0.10: gemma4:e4b is the new default for 'general' subtier. It
  // outperforms qwen2.5:3b on all quality dimensions while being fast
  // enough for interactive use (2.5s p50 on RTX 4090). qwen2.5:3b
  // remains the Option A target for pre-computed answers in the hook.
  let t0Model;
  let t0Subtier = 'general';
  if (CODE_SUBTIER_RE.test(p)) {
    t0Model = MODELS.ollama_code;
    t0Subtier = 'code';
  } else if (MATH_SUBTIER_RE.test(p)) {
    t0Model = MODELS.ollama_math;
    t0Subtier = 'math';
  } else if (category === 'reasoning_intermediate' || category === 'ambiguous_default') {
    t0Model = MODELS.ollama_reason;
    t0Subtier = 'reason';
  } else {
    // v0.10: gemma4 as default general model (was qwen2.5:3b)
    t0Model = MODELS.ollama_general;
    t0Subtier = 'general';
  }

  // v0.9.1: hw-aware T0 model — override terse fallback with recommended model
  // from hw-capability.json (passed via env var by inject_context.js).
  // Only applies to 'general' subtier; code/math/reason specialists keep their models.
  if (t0Subtier === 'general' && process.env.FRUGAL_HW_RECOMMENDED_T0) {
    t0Model = process.env.FRUGAL_HW_RECOMMENDED_T0;
  }

  // ── MULTI-PROVIDER SMART ROUTING (v0.10) ────────────────────────────
  // For each tier, pick the cheapest model from available providers.
  // Provider availability: check env vars (keys) or known plan type.
  // Claude subagents (Sonnet/Opus) always available via Claude Code.
  // Direct API calls need their own keys.
  const HAS_DEEPSEEK = !!process.env.DEEPSEEK_API_KEY;
  const HAS_GEMINI = !!(process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY);
  const HAS_OPENAI = !!process.env.OPENAI_API_KEY;
  const HAS_XAI = !!process.env.XAI_API_KEY;
  const HAS_MISTRAL = !!process.env.MISTRAL_API_KEY;

  // T1 alternatives: pick cheapest available
  // DeepSeek V3 ($0.27/$1.10) < Gemini Flash ($0.30/$2.50) < Mistral ($0.50/$1.50) < Haiku ($1/$5)
  let t1Model = MODELS.haiku;
  let t1Backend = 'claude_subagent'; // Haiku via subagent always works
  let t1Subagent = 'cheap-triage';
  if (HAS_DEEPSEEK) { t1Model = 'deepseek-v3'; t1Backend = 'deepseek_api'; }
  else if (HAS_GEMINI) { t1Model = 'gemini-2.5-flash'; t1Backend = 'gemini_api'; }
  else if (HAS_MISTRAL) { t1Model = 'mistral-large-3'; t1Backend = 'mistral_api'; }

  // T2 alternatives: pick cheapest available
  // Gemini Pro ($1.25/$10) < o3 ($2/$8) < Sonnet ($3/$15)
  let t2Model = MODELS.sonnet;
  let t2Backend = 'claude_subagent';
  let t2Subagent = 'model-reasoner';
  if (HAS_GEMINI) { t2Model = 'gemini-2.5-pro'; t2Backend = 'gemini_api'; }
  else if (HAS_OPENAI) { t2Model = 'o3'; t2Backend = 'openai_api'; }

  // T3: Opus via Claude Code (always available). Alternative: Grok 4 if xAI key present
  // But T3 = architecture/security — quality matters more than cost. Keep Opus unless user overrides.
  let t3Model = MODELS.opus;
  let t3Backend = 'claude_subagent';
  let t3Subagent = 'model-architect';

  const backend = {
    T0: { recommended_backend: 'ollama', recommended_model: t0Model, suggested_subagent: 'local-summarizer' },
    T1: { recommended_backend: t1Backend, recommended_model: t1Model, suggested_subagent: t1Subagent },
    T2: { recommended_backend: t2Backend, recommended_model: t2Model, suggested_subagent: t2Subagent },
    T3: { recommended_backend: t3Backend, recommended_model: t3Model, suggested_subagent: t3Subagent },
  }[tier];

  const promptFeatures = extractPromptFeatures(p);

  const result = {
    task_category: category,
    risk_level: risk,
    tier,
    ...backend,
    confidence: Math.round(confidence * 100) / 100,
    escalation_rule,
    reasoning,
    anthropic_key_present: anthropicKey,
    prompt_length: len,
    file_hint_count: fileMatches,
    quality_intent: qualityIntent,
    t0_subtier: tier === 'T0' ? t0Subtier : null,
    // v0.9.1: prompt features (derived booleans, never raw text)
    ...promptFeatures,
    // v0.10: retraining foundation — provenance + complexity
    algorithm_version: ALGORITHM_VERSION,
    prompt_complexity_score: computeComplexity(len, fileMatches, high, med, low, promptFeatures),
  };

  // ── USER OVERRIDE (highest priority short of HIGH_RISK guardrail) ────────
  // Detect "usa o opus" / "@sonnet" / "with haiku" / "sem opus" and pin
  // tier accordingly. Upgrades are always allowed. Downgrades are refused
  // when the prompt carries any HIGH_RISK signal — we'd rather burn an Opus
  // turn the user doesn't want than route a deploy to Ollama.
  const override = detectUserOverride(p);
  if (override) {
    const TIER_ORDER_LOCAL = ['T0', 'T1', 'T2', 'T3'];
    const currentIdx = TIER_ORDER_LOCAL.indexOf(result.tier);

    if (override.kind === 'negative') {
      // "sem opus" → demote one tier from current (or pin at T2 if at T3).
      // Refuse demotion under HIGH_RISK.
      if (high === 0 && currentIdx > 0) {
        const newTier = TIER_ORDER_LOCAL[Math.max(0, currentIdx - 1)];
        const newBackend = {
          T0: { recommended_backend: 'ollama',           recommended_model: MODELS.ollama_terse, suggested_subagent: 'local-summarizer' },
          T1: { recommended_backend: 'anthropic_api',    recommended_model: MODELS.haiku,        suggested_subagent: 'cheap-triage' },
          T2: { recommended_backend: 'claude_subagent',  recommended_model: MODELS.sonnet,       suggested_subagent: 'model-reasoner' },
          T3: { recommended_backend: 'claude_subagent',  recommended_model: MODELS.opus,         suggested_subagent: 'model-architect' },
        }[newTier];
        result.tier = newTier;
        Object.assign(result, newBackend);
        result.confidence = 0.99;
        result.escalation_rule = 'user_override_negative';
        result.reasoning = `${result.reasoning}; user_override_negative ("${override.raw}") → ${newTier}`;
        result.user_override = {
          kind: 'negative',
          blocked: override.blocked,
          honored: true,
          original_tier: TIER_ORDER_LOCAL[currentIdx],
        };
      } else {
        // Refused
        result.user_override = {
          kind: 'negative',
          blocked: override.blocked,
          honored: false,
          reason: high > 0 ? 'high_risk_signal_present' : 'already_at_T0',
        };
        result.reasoning = `${result.reasoning}; user_override_negative refused (${result.user_override.reason})`;
      }
    } else {
      // positive / forced / assigned / short — pin to requested model.
      const target = USER_OVERRIDE_MODELS[override.model];
      if (target) {
        const targetIdx = TIER_ORDER_LOCAL.indexOf(target.tier);
        const isDowngrade = targetIdx < currentIdx;

        if (isDowngrade && high > 0) {
          // Refused: high-risk prompts cannot be routed to a cheaper tier
          // even by explicit user request. Doctrine guardrail.
          result.user_override = {
            kind: override.kind,
            requested: override.model,
            label: target.label,
            honored: false,
            reason: 'high_risk_signal_present',
            original_tier: TIER_ORDER_LOCAL[currentIdx],
          };
          result.reasoning = `${result.reasoning}; user_override → ${target.label} REFUSED (high-risk signal: cannot downgrade)`;
          result.escalation_rule =
            result.escalation_rule === 'none'
              ? 'user_override_refused_high_risk'
              : `${result.escalation_rule}+user_override_refused`;
        } else {
          // Honored. Pin tier + model + backend to user's choice.
          result.tier = target.tier;
          result.recommended_model = target.model;
          result.recommended_backend = target.backend;
          result.suggested_subagent =
            target.tier === 'T0' ? 'local-summarizer'
              : target.tier === 'T1' ? 'cheap-triage'
              : target.tier === 'T2' ? 'model-reasoner'
              : 'model-architect';
          result.confidence = 0.99;
          result.escalation_rule = `user_override_${override.kind}`;
          result.reasoning = `${result.reasoning}; user_override → ${target.label} (${override.kind}: "${override.raw}")`;
          result.user_override = {
            kind: override.kind,
            requested: override.model,
            label: target.label,
            honored: true,
            original_tier: TIER_ORDER_LOCAL[currentIdx],
          };
        }
      }
    }
  }

  // MD Enrichment — apply Router Context overrides from project CLAUDE.md
  const ctx = readRouterContext();
  const TIER_ORDER = ['T0', 'T1', 'T2', 'T3'];

  if (ctx.complexity_bias && TIER_ORDER.includes(ctx.complexity_bias)) {
    const floor = TIER_ORDER.indexOf(ctx.complexity_bias);
    const current = TIER_ORDER.indexOf(result.tier);
    if (current < floor) {
      result.tier = ctx.complexity_bias;
      result.reasoning += ' +complexity_bias';
    }
  }

  if (ctx.sensitive_patterns) {
    const patterns = ctx.sensitive_patterns.split(',').map((s) => s.trim().replace(/^["']|["']$/g, ''));
    for (const pat of patterns) {
      if (pat && p.toLowerCase().includes(pat.toLowerCase())) {
        const current = TIER_ORDER.indexOf(result.tier);
        if (current < 2) {
          result.tier = 'T2';
          result.reasoning += ' +sensitive';
        }
        break;
      }
    }
  }

  if (ctx.fast_patterns) {
    const patterns = ctx.fast_patterns.split(',').map((s) => s.trim().replace(/^["']|["']$/g, ''));
    for (const pat of patterns) {
      if (pat && p.toLowerCase().includes(pat.toLowerCase())) {
        result.tier = 'T0';
        result.reasoning += ' +fast_pattern';
        break;
      }
    }
  }

  // If MD overrides changed tier, refresh the backend block
  if (result.tier !== tier) {
    const overrideBackend = {
      T0: { recommended_backend: 'ollama', recommended_model: MODELS.ollama_terse, suggested_subagent: 'local-summarizer' },
      T1: { recommended_backend: 'anthropic_api', recommended_model: MODELS.haiku, suggested_subagent: 'cheap-triage' },
      T2: { recommended_backend: 'claude_subagent', recommended_model: MODELS.sonnet, suggested_subagent: 'model-reasoner' },
      T3: { recommended_backend: 'claude_subagent', recommended_model: MODELS.opus, suggested_subagent: 'model-architect' },
    }[result.tier];
    Object.assign(result, overrideBackend);
  }

  setCache(prompt || '', result);
  return result;
}

(async () => {
  try {
    const prompt = await readPrompt();
    const result = classify(prompt);
    process.stdout.write(JSON.stringify(result, null, 2) + '\n');
  } catch (err) {
    process.stdout.write(
      JSON.stringify({
        recommended_backend: 'claude_session',
        recommended_model: 'session-default',
        confidence: 0,
        escalation_rule: 'classifier_error_fallthrough',
        error: String(err && err.message || err),
      }) + '\n'
    );
  }
})();
