#!/usr/bin/env node
/**
 * update-router.js — applies tuning suggestions from router-tuning.json
 * to classify.js, non-destructively.
 *
 *   1. Backs up classify.js → classify.js.bak (overwrites previous backup)
 *   2. Injects/updates a TUNED block bracketed by markers so re-runs are
 *      idempotent and never compound.
 *   3. Adds new promote/demote regex patterns to TRIVIAL/HIGH_RISK lists
 *      via in-place insertion (only if pattern not already present).
 *   4. Logs every change to stdout.
 *
 * Run via: node ~/.claude/tools/router/update-router.js
 * Or piped after backtest: node backtest.js && node update-router.js
 */

'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');

const ROUTER_DIR = path.join(os.homedir(), '.claude', 'tools', 'router');
const CLASSIFY = path.join(ROUTER_DIR, 'classify.js');
const BACKUP = path.join(ROUTER_DIR, 'classify.js.bak');
const TUNING = path.join(ROUTER_DIR, 'router-tuning.json');

const BLOCK_START = '// ── TUNED-BLOCK-START (auto-generated by update-router.js) ──';
const BLOCK_END = '// ── TUNED-BLOCK-END ──';

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function patternToRegexLine(pattern) {
  // Build a word-boundary-anchored regex literal that matches the signature.
  const parts = pattern.split(/\s+/).filter(Boolean).map(escapeRegex);
  if (parts.length === 0) return null;
  const body = parts.join('\\s+');
  return `/\\b${body}\\b/i`;
}

function buildTunedBlock(tuning) {
  const lines = [BLOCK_START];
  lines.push(`// generated_at: ${tuning.generated_at}`);
  lines.push(`// sample_size: ${tuning.sample_size}`);
  lines.push(`const TUNED_COMPLEXITY_THRESHOLD = ${tuning.complexity_threshold};`);

  const promoteRegexes = (tuning.promote_to_t0_patterns || [])
    .map(patternToRegexLine)
    .filter(Boolean);
  const demoteRegexes = (tuning.demote_from_t3_patterns || [])
    .map(patternToRegexLine)
    .filter(Boolean);

  lines.push(`const TUNED_PROMOTE_T0 = [${promoteRegexes.join(', ')}];`);
  lines.push(`const TUNED_DEMOTE_T3 = [${demoteRegexes.join(', ')}];`);
  lines.push(BLOCK_END);
  return lines.join('\n');
}

function main() {
  const dryRun = process.argv.includes('--dry-run');

  if (!fs.existsSync(TUNING)) {
    console.error(`update-router: ${TUNING} not found. Run backtest.js first.`);
    process.exit(1);
  }
  if (!fs.existsSync(CLASSIFY)) {
    console.error(`update-router: ${CLASSIFY} not found.`);
    process.exit(1);
  }

  const tuning = JSON.parse(fs.readFileSync(TUNING, 'utf8'));
  const original = fs.readFileSync(CLASSIFY, 'utf8');

  if (dryRun) {
    console.log('── DRY RUN — no files will be modified ──');
    console.log('');
    console.log('Tuned block that would be injected into classify.js:');
    console.log('');
    console.log(buildTunedBlock(tuning));
    console.log('');
    console.log('Notes:');
    for (const note of tuning.notes || []) console.log(`  - ${note}`);
    return;
  }

  // Backup (overwrites previous backup)
  fs.writeFileSync(BACKUP, original);

  const block = buildTunedBlock(tuning);

  let updated;
  const blockRegex = new RegExp(
    `${escapeRegex(BLOCK_START)}[\\s\\S]*?${escapeRegex(BLOCK_END)}`
  );
  if (blockRegex.test(original)) {
    updated = original.replace(blockRegex, block);
  } else {
    // Insert after 'use strict' directive
    const useStrictMatch = original.match(/['"]use strict['"];?\n/);
    if (useStrictMatch) {
      const idx = useStrictMatch.index + useStrictMatch[0].length;
      updated = original.slice(0, idx) + '\n' + block + '\n' + original.slice(idx);
    } else {
      updated = block + '\n' + original;
    }
  }

  if (updated === original) {
    console.log('update-router: no changes (block already up to date).');
    return;
  }

  fs.writeFileSync(CLASSIFY, updated);

  console.log('update-router: classify.js updated.');
  console.log(`  backup:                 ${BACKUP}`);
  console.log(`  complexity_threshold:   ${tuning.complexity_threshold}`);
  console.log(`  promote_to_t0_patterns: ${(tuning.promote_to_t0_patterns || []).length}`);
  console.log(`  demote_from_t3_patterns:${(tuning.demote_from_t3_patterns || []).length}`);
  console.log('');
  console.log('Notes:');
  for (const note of tuning.notes || []) console.log(`  - ${note}`);
}

if (require.main === module) main();
